@echo off
axmol build -p win32 -DAX_BUILD_TESTS=OFF -DAX_ENABLE_EXT_ASSETMANAGER=OFF -DAX_ENABLE_EXT_PARTICLE3D=OFF -DAX_ENABLE_EXT_PHYSICS_NODE=OFF -DAX_ENABLE_EXT_SPINE=OFF -DAX_ENABLE_EXT_DRAGONBONES=OFF -DAX_ENABLE_EXT_COCOSTUDIO=OFF -DAX_ENABLE_EXT_FAIRYGUI=OFF -DAX_ENABLE_EXT_JSONDEFAULT=OFF -DAX_ENABLE_EXT_SDFGEN=OFF
